language: objective-c
osx_image: xcode12
os: osx
rvm: 2.7.2

cache:
  bundler: true
  cocoapods: true
  directories:
  - .build # Swift Package Manager
  - /Users/travis/.rvm/ # RVM

before_install:
  - gem install bundler:2.1.4

stages:
  - name: "Unit Tests"
    if: type = push
  - name: Validate
    if: type = pull_request

jobs:
  include:
    - stage: Validate
      name: Cocoapods
      script: bundle exec fastlane lint_cocoapods
    - name: "Swift Package Manager"
      script: bundle exec fastlane lint_swift_package_manager
    - name: "Build Demo App"
      script: bundle exec fastlane build_example --env ios
    - stage: "Unit Tests"
      name: iOS
      before_script: xcrun simctl list -j
      script: bundle exec fastlane test --env ios
    - name: macOS
      script: bundle exec fastlane test --env macos
    - name: tvOS
      before_script: xcrun simctl list -j
      script: bundle exec fastlane test --env tvos

before_cache:
  - rvm cleanup all
  - bundle clean
  - swift package clean
